package com.example.lovebirds.util

val DATA_USERS ="Users"
val DATA_NAME ="name"
val DATA_AGE ="age"
val DATA_EMAIL ="email"
val DATA_GENDER ="gender"
val DATA_GENDERPREFFERENCE ="preferedgender"
val GENDER_MALE ="male"
val GENDER_FEMALE ="female"
val DATA_IMAGEURL="imageUrl"
val DATA_SWIPES_LEFT="swipesleft"
val DATA_SWIPE_RIGHT ="swipesright"
val DATA_MATCHES ="matches"
val DATA_ABOUT ="about"
val DATA_CHATS ="Chats"
val DATA_MESSAGES="Messages"